### ISSUE TITLE
Loader doesn't animate until after whole page has rendered

### ISSUE THREAD

**Issue by aej11a** [danilowoz/react-content-loader#151]
## What did you do? 
To confirm the issue:

```
    <MyLoader/>
    <ul>
        {data.map((item, index) => {
             return (
                 {Content with text, images, etc)
             )
        }}
    </ul>
```

## What did you expect to happen?
Loader should start animating on page load

## What happened actually?
Page loads, loader renders statically. After all the data and images are fully loaded, the loader animates.

### Which versions of react-content-loader, and which browser are affected by this issue?
Chrome, most recent published version of react-content-loader

**Comment by danilowoz** [comment]
Hey @aej11a, thanks for reporting it.

I could reproduce the problem and it looks an SVG issue because the output of `react-content-loader` is just a plain SVG with no javascript interaction. 

I can suggest you two approach to improve the experience (will not solve the main problem):
- Use lazy-load in images, which will unload the main thread;
- Remove the animation of loader `<ContetLoader animated={false} />`;

Let me know if it was helpful to you
