### ISSUE TITLE
Question/Feature: Fallback Support / Browser Test

### ISSUE THREAD

**Issue by countravioli** [danilowoz/react-content-loader#197]
It could be neat to have some sort of fallback support for browsers where animation isn't supported. I know supporting IE11 isn't very much on the top of peoples minds but might be nice. If you aren't aware, the behavior I see is my loader boxes not scaled to the correct size and with no animation.

That being said, I can obviously implement my own wrapper that does a different loading experiences where this isn't supported. However, I was curious if anyone already had a function that tested the environment and whether or not `react-content-loader` was supported. Thanks!

**Comment by danilowoz** [comment]
Hey @countravioli, thanks for submitting your question here.

The package doesn't have any kind of polyfill or fallback because the result of render is a regular SVG/HTML, so everything depends on the browser support. Also, the purpose of the package is to deliver an interface between React and SVG, only with some basic configurations to achieve the shape and the animation option.

If the oldest browsers are a requirement is your project, I'd recommend you to use GIF images in the place of SVG since some specifications of SVG are not fully supported in every browser.

I'm still planing a way to export the loading in the GIF on the [creator tool](http://danilowoz.com/create-content-loader), but this has proved difficult to build. 

So let me know if it's a possible way for you, thanks

**Comment by countravioli** [comment]
@danilowoz thanks for getting back to me. I'm not interested in this project targetting all browsers because I realized that becomes a pain to support. I guess what I was hinting at was possibly a utility function provided the library that would return true/false if the client is supported, or a callback passed into the component that could be executed if the client is not supported. 

In my mind, the use case is that you would use either of these to provide a legacy browser / fallback display for loading. Cheers!

**Comment by danilowoz** [comment]
My bad, I got completely wrong your question.

In my research I found a couple of solutions on how to check if a browser supports the animate feature or not:

- `window.SVGAnimateElement`
- `document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#SVG-Animation", "1.1")`
- Or even use https://modernizr.com/

Fonts: https://voormedia.com/blog/2012/10/displaying-and-detecting-support-for-svg-images

I wouldn't add any callback or method in the package itself, but a mention in the documentation would be worth it.
