### ISSUE TITLE
Shape's border has a little bit of distortion on a dark background

### ISSUE THREAD

**Issue by pascualmj** [danilowoz/react-content-loader#238]
Platform: React Native (IOS and Android).

I found that when shapes are used on a dark background, the borders show a little bit of distortion.
`<Rect x="48" y="8" rx="3" ry="3" width="88" height="6" />`

The following image show this issue:
![Shape's border has a little bit of distortion on a dark background](https://i.ibb.co/tz9J7yy/image-image.png "Shape's border has a little bit of distortion on a dark background")

Version of react-content-loader used: 6.0.1

**Comment by danilowoz** [comment]
Hey @pascualmj, it seems that this's the default behavior of the device render or even of how the `react-native-svg` handles the shapes. Unfortunately, there is nothing I can't do here, since `react-content-loader` only creates an interface between the SVG's shapes and the RN itself. I'd suggest trying out different values to make the border smoother and see how it looks in a real device.
