### ISSUE TITLE
Top-down animation

### ISSUE THREAD

**Issue by vlkpa** [danilowoz/react-content-loader#255]
Hello all, there is default animation from left to right, but is there some way how to make top-down animation?

**Comment by danilowoz** [comment]
Hey @vlkpa, currently, react-content-loader doesn't support this kind of behavior, and there is no plan to support it in the short term, as it would increase the complexity and the bundle size in such a way that doesn't worth it for a while.

So far, it hasn't had much demand for this feature, but if more people ask for this in the future, I'd definitely consider this. Otherwise, feel free to propose this feature in a pull request. So, I'll leave this issue open in case anybody else searches for this feature. 

Thanks for your feedback!
