### ISSUE TITLE
[proposal] Restructure API

### ISSUE THREAD

**Issue by Andarist** [danilowoz/react-content-loader#69]
Imho, for such a simple component with simple variants it would be much better to just export `Wrap` as default and all various flavours as named exports. This would be a breaking change, but I think it's better to export separate components that are composed from others, than to hardcore all of them as dependency (through `props.type`) of a single component. At the moment if Im interested in lets say Facebook variant only, I need to pull **all** variants into my app. The proposed change would allow me and others to pull only a subset of those variants.

**Comment by danilowoz** [comment]
Great! 

So you're completely right about on this point. A short time ago I saw the same problem, too many specifics components within the project, but at the beginning of the project, it made sense. Because I still didn't have the custom mode. 

Then I had the idea to create the [create-react-content-loader](http://danilowoz.com/create-react-content-loader/), so all the styled components aren't more necessary. However, I haven't done it so far, my mistakes.  

BUT, I would like that component would have an initial state, I don't know if the Facebook-style or another one. What do you think? makes sense?

**Comment by Andarist** [comment]
> So you're completely right about on this point. A short time ago I saw the same problem, too many specifics components within the project, but at the beginning of the project, it made sense. Because I still didn't have the custom mode.

Agreed, I would certainly not split this up myself at the beginning of the project.

> Then I had the idea to create the create-react-content-loader, so all the styled components aren't more necessary. However, I haven't done it so far, my mistakes.

Looks really cool!

> BUT, I would like that component would have an initial state, I don't know if the Facebook-style or another one. What do you think? makes sense?

Personally I'd prefer something really simple as default - like a single rectangular, but this is totally up to you. I'll get the ball rolling and will send up a simple PR in a moment.
